#!/bin/bash

sudo pacman -S ccze \
python-pip \
dropbox \
vim \
jdk8-openjdk \
intellij-idea-community-edition \
ttf-hack \
chromium

chmod +x ./vimstuff.sh
./vimstuff.sh

chmod +x ./gitstuff.sh
./gitstuff.sh
